services:
  grafana:
    user: root
    container_name: 'guilhermearpassos-sqlsights-app'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.2.1}
        development: ${DEVELOPMENT:-true}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dist:/var/lib/grafana/plugins/guilhermearpassos-sqlsights-app
      - ../provisioning:/etc/grafana/provisioning
      - ../dashboards:/var/lib/grafana/dashboards
      - ..:/root/guilhermearpassos-sqlsights-app

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.guilhermearpassos-sqlsights-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: guilhermearpassos-sqlsights-app
